### PR TITLE
TC-2204 Optimize Fluentd configuration

### PR DESCRIPTION
**Pull request by keithwoody**
Clean up fluentd settings by removing unused source configs, adding log sources that were left out of the initial implementation, adding the correct settings for the kubernetes metadata extraction filter and updating the buffer type to match fluentd recommendations. Also brings the Jenkinsfile up to date with latest build process.

Fixing the kubernetes metadata filter extracts info from the log tag and makes the log output easier to interpret.

```
{"log":"/usr/local/bundle/gems/rake-10.5.0/lib/rake/application.rb:150:in `invoke_task'\n",
"stream":"stdout",
"docker":{"container_id": "2276ebb46b953e6d7c7c883ef9170f1f77366c1929e052566c1f000b2988d717"},
"kubernetes":{
  "container_name": "worker-ui-resque",
  "namespace_name": "amazon-public-cloud-qe02",
  "pod_name": "worker-ui-resque-843866053-k93j5",
  "pod_id": "921f40f2-aa8c-11e7-a800-0a55c4c8b216",
"labels":{
  "app": "worker-ui-resque",
  "pod-template-hash": "843866053"},
"host": "kube-node-qe02-001.secure.cf3.us",
"master_url": "https://10.96.0.1:443/api"}}
```

Changing the buffer type (after reading the [Caution section of the buf_file plugin overview](https://docs.fluentd.org/v0.12/articles/buf_file)) got rid of the buffer files in the nfs/fluentd directory, but tailing live logs can still be done from the control plane via `kubectl logs pod_id-hash`. This was partly to stop fluentd warnings about missing files that were clearly old buffers that went missing after a pod deletion or shutdown, but also to reduce the chances of losing data per the caution linked above.

jetpack

### CODE REVIEW

**Comment by maj** [comment]
I don't know enough about this to review, maybe add Ron?

**Review by rmcclaincf — APPROVED** [review]
This if fine.  I do have reservations about the overall fluentd architecture and the use of NFS that are out of scope for now.  But really, I'd prefer to use the forward output plugin instead of file, and have another set of fluentd containers that do any aggregation/filtering and the writing directly into influx/logstash/splunk/etc.

**Comment by onewland** [comment]
Is that metadata going to be on every single log line? It's maybe clearer than what we currently have but I think what we'd mainly want is the pod ID and the app label.

**Comment by keithwoody** [comment]
@onewland the metadata is already present in every line as a tag created by fluentd i.e. `kubernetes.var.log.containers.worker-ui-resque-843866053-k93j5_amazon-public-cloud-qe02_worker-ui-resque-2276ebb46b953e6d7c7c883ef9170f1f77366c1929e052566c1f000b2988d717.log` the metadata filter parses it to the more readable format above. 

Now that you bring it up, once it's parsed we could:
1. change the entry tag to be less verbose (something like `qe02.worker-ui-resque.921f40f2-aa8c-11e7-a800-0a55c4c8b216`) 
2. send all or some of the fields listed in the description

Personally I think the metadata in that format could be very useful in diagnosing/debugging issues with CFSecure.

**Review by onewland — APPROVED** [review]

**Pull request merged**
